### PR TITLE
Curate Python resources and add to sidebar

### PR DESCRIPTION
**Pull request by bhrutledge**
I removed ones that didn't feel right for this list, due to the overall quality, staleness, or because they cost money.

### CODE REVIEW

**Comment by bhrutledge** [comment]
@jonkiparsky FYI

**Comment by nedbat** [comment]
Maybe for the ones that cost money, we can just segregate them into a section that makes that clear.  It will keep people from proposing to add them to the list.

In the Adventofcode paragraph, let's just remove the timed competition part. It will scare away the people reading this page, who won't be competing on time anyway.

**Comment by nedbat** [comment]
Let's also add a sentence about how to add things to the page.

**Comment by bhrutledge** [comment]
@nedbat I tweaked the list based on your suggestions.

Also, I attempted to make the "edit this page" footer more helpful, and opted for a jump link to that in the `NOTE`, rather than duplicating the links.

**Comment by nedbat** [comment]
Nice, merge it! :)

**Comment by bhrutledge** [comment]
It's live. I snuck in a background fade to help people notice the links after the jump.

https://about.bostonpython.com/resources#edit-page

**Comment by nedbat** [comment]
I like the fade, it's snazzy.  I tweaked the layout a touch.

**Pull request merged**
